### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by onion797jp** [onion797jp/github-projects-playground#4]
Task List
- [ ] Create a `docs` folder
- [ ] Create a new `index.md` document
- [ ] Turn on GitHub Pages
- [ ] Decide if we want to go with sometime more complex
